services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_lm
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaTescaro123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb_lm
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork 

  lojadoseumanoel:
    build:
      context: .
      dockerfile: ./LojaDoSeuManoel.API/Dockerfile
    container_name: lojadoseumanoel
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - mongodb
    networks:
      - mynetwork


volumes:
  sqlserver_data:
  mongodb_data:

networks:
  mynetwork:
    driver: bridge
